### PR TITLE
(maint) Add Apache2 LICENSE file

### PR DESCRIPTION
**Pull request by mwaggett**

### CODE REVIEW

**Comment by mwaggett** [comment]
I copied this from the puppet repo. lmk if there's a different project's license file we'd prefer.

**Comment by grimradical** [comment]
LGTM - only real nuance here is that I think some ecosystems might have a more "preferred" license. Like, um, maybe if you're opening up a clojure library you'd want to use EPL vs. Apache because that's the dominant license for the ecosystem. But Apache2 has historically been our goto "default", so I don't see the harm in codifying that here!

**Comment by mwaggett** [comment]
yeah, I was going with Apache 2 since afaik that's what we've always used for our internal stuff. But I guess if a team wants a different license for their project, they can override that in their repo.

**Comment by binford2k** [comment]
FWIW, license files won't be surfaced as a default. But in our template repository instructions we can point to a simple decision tree for choosing the handful of licenses we recommend.

Do we have a list of licenses that legal has approved for use in our projects?

**Comment by mwaggett** [comment]
@binford2k ahh, you're saying that even with this file in this repo, new repos won't be auto-populated? that's a bummer, but I still think it can't hurt to have this here, in case people wanna copy+paste.

There's a list of approved licenses for third-party software [here](https://github.com/puppetlabs/components-licenses/blob/2019.1.x/license_key.yaml), but I don't know of a specific list for Puppet projects. I thought we just used Apache2 everywhere tbh. @shrug ^do you know if anything like this exists?

**Comment by binford2k** [comment]
Right. But the template repo that @shrug is working on [includes it](https://github.com/puppetlabs/template_repo/blob/master/LICENSE), so new repos started from there can get it by default.

This repo I think should have a short "here are the 3 licenses to choose from" decision tree and then text of them in a `/licenses` subdirectory.

**Comment by mwaggett** [comment]
I'm just going to close this, since @shrug's repo already has a LICENSE.

If we decide a decision tree is a good idea, it should live in Confluence. If it stays here, every new repo will end up with extra license files they'll have to clean up.

**Pull request closed without merging**
